databases:
  - name: numberclassificationdb
    plan: free
    databaseName: numberclassification
    user: numberclassification

services:
  - type: web
    plan: free
    name: numberclassification
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn number_classification.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: number_classificationdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4